name: Scrape latest help

on:
  workflow_dispatch:
  schedule:
    - cron:  '1 15 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Configure Python with pip cache
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        cache: 'pip'
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: '**/.github/workflows/*.yml'
    - name: Install Python dependencies
      run: pip install -U -r requirements.txt
    - name: Configure Git for commits
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
    - name: Use Griffe to scrape sqlite-utils
      run: |-
        mkdir -p griffe
        griffe sqlite_utils > griffe/sqlite-utils.json
    - name: Commit and push if it changed
      run: |-
        git add -A
        timestamp=$(date -u)
        git commit -m "sqlite-utils: ${timestamp}" || exit 0
        git push
    - name: Compile latest SQLite
      run: |-
        cd /tmp
        git clone --depth 1 https://github.com/sqlite/sqlite
        mkdir /tmp/bld
        cd /tmp/bld
        ../sqlite/configure
        make sqlite3.c
        gcc shell.c sqlite3.c -lpthread -ldl
        ./a.out --version
    - name: Scrape sqlite3 help
      run: |-
        python sqlite3_help.py /tmp/bld/a.out > sqlite3-help.md
    - name: Commit and push if it changed
      run: |-
        git add -A
        timestamp=$(date -u)
        git commit -m "sqlite3: ${timestamp}" || exit 0
        git push
    - name: Scrape GitHub GraphQL API schema
      run: |-
        mkdir -p github
        npx get-graphql-schema https://api.github.com/graphql \
          -h 'Authorization=Bearer ${{ secrets.GITHUB_TOKEN }}' > github/github.graphql
    - name: Commit and push if it changed
      run: |-
        git add -A
        timestamp=$(date -u)
        git commit -m "GitHub: ${timestamp}" || exit 0
        git push
    - name: Scrape Vercel
      run: |-
        python vercel_commands.py
    - name: Commit and push if it changed
      run: |-
        git add -A
        timestamp=$(date -u)
        git commit -m "Vercel: ${timestamp}" || exit 0
        git push
    - name: Scrape Azure
      run: |-
        sh azure.sh
    - name: Commit and push if it changed
      run: |-
        git add -A
        timestamp=$(date -u)
        git commit -m "Azure: ${timestamp}" || exit 0
        git push
    - name: Scrape Fly
      run: |-
        ./fly.sh
        # Grab the GraphQL schema too
        npx get-graphql-schema https://api.fly.io/graphql > flyctl/fly.graphql
    - name: Commit and push if it changed
      run: |-
        git add -A
        timestamp=$(date -u)
        git commit -m "Fly: ${timestamp}" || exit 0
        git push
    - name: Scrape AWS
      run: |-
        python -m pip install -U awscli
        python -m awscli --version > aws/aws-version.txt
        cat aws/aws-version.txt
        python aws_commands.py
    - name: Commit and push if it changed
      run: |-
        git add -A
        timestamp=$(date -u)
        git commit -m "AWS: ${timestamp}" || exit 0
        git pull --rebase
        git push
